export const DEFAULT_MEMBERS = [
  {
    name:       'Alex Kim',
    role:       'Head of Engineering',
    timezone:   'America/New_York',
    workStart:  '09:00',
    workEnd:    '18:00',
    colorIndex: 0,
  },
  {
    name:       'Priya Sharma',
    role:       'Product Manager',
    timezone:   'Asia/Kolkata',
    workStart:  '10:00',
    workEnd:    '19:00',
    colorIndex: 1,
  },
  {
    name:       'Tom Eriksen',
    role:       'CEO',
    timezone:   'Europe/Stockholm',
    workStart:  '08:00',
    workEnd:    '17:00',
    colorIndex: 2,
  },
  {
    name:       'Lena Fischer',
    role:       'Lead Designer',
    timezone:   'Europe/Berlin',
    workStart:  '09:00',
    workEnd:    '18:00',
    colorIndex: 3,
  },
  {
    name:       'Zara Ahmed',
    role:       'DevOps Engineer',
    timezone:   'Africa/Lagos',
    workStart:  '08:00',
    workEnd:    '17:00',
    colorIndex: 7,
  },
  {
    name:       'Marcus Liu',
    role:       'Frontend Developer',
    timezone:   'Asia/Tokyo',
    workStart:  '10:00',
    workEnd:    '19:00',
    colorIndex: 4,
  },
  {
    name:       'Sofia Rivera',
    role:       'Data Scientist',
    timezone:   'America/Los_Angeles',
    workStart:  '09:00',
    workEnd:    '17:30',
    colorIndex: 6,
  },
  {
    name:       'James Okafor',
    role:       'Backend Developer',
    timezone:   'Africa/Lagos',
    workStart:  '09:00',
    workEnd:    '18:00',
    colorIndex: 5,
  },
]